### ISSUE TITLE
Parser: CST + AST

### ISSUE THREAD

**Issue by livioso** [livioso/cpib#11]
CommandIfThen
Program

The following issue should help to keep track of the implemented production _(functions)_ for the parser.

**Pretty sure the following productions are complete / correct / tested / done:** :see_no_evil: 
- program
- optionalGlobalDeclarations
- declarations
- declaration
- functionDeclaration
- storageDeclaraction
- parameterList
- optionalParameters a0aff62
- parameter fdff4e5
- repeatingOptionalDelcarations e88d192
- optionalLocalStorageDeclaractions cf6ee09
- repeatingOptionalStorageDeclarations
- blockCommand
- command 32836f6
- optionalMechMode
- expression
- term1
- relOprTerm2
- expressionList
- optionalExpressions
- repeatingOptionalExpressions aa07cf7
- boolOprTerm1 9eccf56
- repeatingOptionalCommands de6d01a
- optionalChangeMode
- typedIdent e36117b
- procedureDeclaration d35c2a93
- typeDelcaration d35c2a93
- optRecordDeclaration d35c2a93
- recordFieldList 7b549ba
- repeatingOptionalParameters
- recordFields
- recordField
- repRecordFields e8b6c51
- term2
- term3
- addOprTerm3
- term4 ee919fa
- multOprTerm4
- dotOprFactor
- factor
- optionalIdent 87b2355

**Missing / TDB:**
- none

@RaphiOriginal please update this issue if you add a production function so we know what's next, thanks. :+1:

**Comment by RaphiOriginal** [comment]
added forgotten productions to the list

**Comment by livioso** [comment]
CST initially completed. :tada:
